# Generated by Django 4.2.1 on 2023-05-18 14:51

import autosallonApp.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('autosallonApp', '0002_alter_category_options_car_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=autosallonApp.models.car_image_upload_path)),
                ('car_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autosallonApp.car')),
            ],
        ),
    ]
