# Generated by Django 4.2.1 on 2023-06-13 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autosallonApp', '0004_rename_resevedlink_car_reservedlink'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='iscompleted',
            field=models.BooleanField(default=False),
        ),
    ]
