# Generated by Django 4.0.3 on 2023-06-14 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autosallonApp', '0005_sale_iscompleted'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=50)),
                ('title', models.CharField(blank=True, max_length=50)),
                ('message', models.TextField()),
            ],
        ),
    ]
