# Generated by Django 4.0.3 on 2023-06-14 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autosallonApp', '0006_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='engine',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='car',
            name='fuel',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='car',
            name='transmission',
            field=models.CharField(default='', max_length=50),
        ),
    ]
