# Generated by Django 4.0.3 on 2023-06-14 11:50

import autosallonApp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autosallonApp', '0007_car_engine_car_fuel_car_transmission'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='image',
            field=models.ImageField(default='reactapp/src/images/No_Image_Available.jpg', upload_to=autosallonApp.models.car_image_upload_path),
        ),
    ]
