# Generated by Django 4.0.3 on 2023-06-14 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autosallonApp', '0008_worker_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='ads',
            field=models.BooleanField(default=False),
        ),
    ]
